spring:
  profiles:
    active: dev,commondb
management:
  endpoints:
    web:
      exposure:
        include: "*"


---
spring:
    profiles : dev
    datasource:
      url: jdbc:mysql://localhost:3306/cleanmasterdb
      username : root
      password : 123456Aa

---
spring:
  profiles : test
  datasource:
    url: jdbc:mysql://localhost:3306/testcleanmasterdb
    username : root
    password : 123456Aa


---
spring:
  profiles : commondb
  datasource :
    driver-class-name : com.mysql.jdbc.Driver
  jpa:
    database-platform : org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate :
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true