spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
    profiles : dev
    datasource:
      url: jdbc:mysql://localhost:3306/cleanmasterdb
      username : root
      password : 123456Aa


