package com.indiacleantool.cleantool.web.models.mobileusermodals.bookingservicerequest;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.indiacleantool.cleantool.web.models.common.timeslots.TimeSlots;
import com.indiacleantool.cleantool.web.models.frontendmodals.staticservice.Services;
import com.indiacleantool.cleantool.web.models.users.company.Company;
import com.indiacleantool.cleantool.web.models.users.employee.Employee;
import com.indiacleantool.cleantool.web.models.users.mobileuser.MobileUser;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import java.util.Date;

@Entity
@NamedStoredProcedureQueries({
        @NamedStoredProcedureQuery(
                name = "sp_Genarate_Service_RequestCode",
                procedureName = "sp_Genarate_Service_RequestCode",
                parameters = {
                        @StoredProcedureParameter(mode = ParameterMode.IN,name = "service_req_id",type = Long.class),
                        @StoredProcedureParameter(mode = ParameterMode.OUT,name = "service_req_code",type = String.class)
                }
        )
})
public class ServiceRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Service code cannot be blank")
    private String serviceCode;

    @NotBlank(message = "Company code cannot be blank")
    private String companyCode;

    @NotBlank(message = "Mobile user code cannot be blank")
    private String mobileUserCode;

    @NotBlank(message = "Time slot code cannot be blank")
    private String timeSlotCode;

    @NotBlank(message = "Service message id cannot be blank")
    private String serviceMsgId;

    @ManyToOne
    @JoinColumn(name = "time_slot_id")
    @JsonIgnore
    private TimeSlots timeSlots;

    @ManyToOne
    @JoinColumn(name = "mobile_user_id")
    @JsonIgnore
    private MobileUser mobileUser;

    @ManyToOne
    @JoinColumn(name = "company_id")
    @JsonIgnore
    private Company company;

    @ManyToOne
    @JoinColumn(name = "service_id")
    @JsonIgnore
    private Services services;

    @OneToOne
    @JoinColumn(name = "assigned_employee_id")
    @JsonIgnore
    private Employee assignedEmployee;

    private String assignedEmployeeCode;

    private  int statusCode;  //Should be assigned by Inner ServiceRequestStatus Enum Class

    private  String statusName;  //Should be assigned by Inner ServiceRequestStatus Enum Class

    private String serviceReqCode;  // Need to generated by runnng Stored procedure

    private Double reqLatitude;

    private Double reqLongitude;


    ////Only for Frontend and Mobile user response
    @Transient
    private String companyName;

    @Transient
    private String mobileUserName;

    @Transient
    private String assignedEmployeeName;

    @Transient
    private String assignedEmployeeMobile;

    @Transient
    private String serviceName;

    @Transient
    private String time;


    public String getAssignedEmployeeCode() {
        return assignedEmployeeCode;
    }

    public void setAssignedEmployeeCode(String assignedEmployeeCode) {
        this.assignedEmployeeCode = assignedEmployeeCode;
    }

    @JsonFormat(pattern = "yyyy-mm-dd")
    private Date created_at;

    @JsonFormat(pattern = "yyyy-mm-dd")
    private Date updated_at;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getServiceCode() {
        return serviceCode;
    }

    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public String getMobileUserCode() {
        return mobileUserCode;
    }

    public void setMobileUserCode(String mobileUserCode) {
        this.mobileUserCode = mobileUserCode;
    }

    public String getTimeSlotCode() {
        return timeSlotCode;
    }

    public void setTimeSlotCode(String timeSlotCode) {
        this.timeSlotCode = timeSlotCode;
    }

    public String getServiceMsgId() {
        return serviceMsgId;
    }

    public void setServiceMsgId(String serviceMsgId) {
        this.serviceMsgId = serviceMsgId;
    }

    public TimeSlots getTimeSlots() {
        return timeSlots;
    }

    public void setTimeSlots(TimeSlots timeSlots) {
        this.timeSlots = timeSlots;
    }

    public MobileUser getMobileUser() {
        return mobileUser;
    }

    public void setMobileUser(MobileUser mobileUser) {
        this.mobileUser = mobileUser;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Services getServices() {
        return services;
    }

    public void setServices(Services services) {
        this.services = services;
    }

    public Employee getAssignedEmployee() {
        return assignedEmployee;
    }

    public void setAssignedEmployee(Employee assignedEmployee) {
        this.assignedEmployee = assignedEmployee;
    }

    public int getStatusCode() {
        return statusCode;
    }

    public void setStatusCode(int statusCode) {
        this.statusCode = statusCode;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    public String getServiceReqCode() {
        return serviceReqCode;
    }

    public void setServiceReqCode(String serviceReqCode) {
        this.serviceReqCode = serviceReqCode;
    }

    public Double getReqLatitude() {
        return reqLatitude;
    }

    public void setReqLatitude(Double reqLatitude) {
        this.reqLatitude = reqLatitude;
    }

    public Double getReqLongitude() {
        return reqLongitude;
    }

    public void setReqLongitude(Double reqLongitude) {
        this.reqLongitude = reqLongitude;
    }

    public Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    public Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }


    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getAssignedEmployeeName() {
        return assignedEmployeeName;
    }

    public void setAssignedEmployeeName(String assignedEmployeeName) {
        this.assignedEmployeeName = assignedEmployeeName;
    }

    public String getAssignedEmployeeMobile() {
        return assignedEmployeeMobile;
    }

    public void setAssignedEmployeeMobile(String assignedEmployeeMobile) {
        this.assignedEmployeeMobile = assignedEmployeeMobile;
    }

    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }


    public String getMobileUserName() {
        return mobileUserName;
    }

    public void setMobileUserName(String mobileUserName) {
        this.mobileUserName = mobileUserName;
    }

    @PrePersist
    protected void onCreate(){
        this.created_at = new Date();
    }

    @PreUpdate
    protected void onUpdate(){
        this.updated_at=new Date();
    }


    public enum ServiceRequestStatus {
        PENDING(100,"Pending"),
        ASSIGNED(101,"Assigned"),
        INPROGRESS(102,"In-Progress"),
        COMPLETED(103,"Completed"),
        CANCELED(104,"Canceled");

        private final int statusCode;
        private final String statusName;
        ServiceRequestStatus(int statusCode, String statusName) {
            this.statusCode=statusCode;
            this.statusName=statusName;
        }

        public int getStatusCode() {
            return statusCode;
        }

        public String getStatusName() {
            return statusName;
        }
    }

}
